# Generated by Django 5.1.6 on 2025-02-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_configuration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Configuration',
            new_name='KeyConfiguration',
        ),
    ]
