# Generated by Django 5.2 on 2025-05-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_alter_customermessage_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pinecone_api_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
