# Generated by Django 5.1.6 on 2025-03-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langchainai', '0005_customermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermessage',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
    ]
